### PR TITLE
add fresno_housing spider

### PR DESCRIPTION
**Pull request by haileyhoyat**
@jpt-c 

so close, need help w _parse_start() (lines#60-84). 
i can get the year and time, having trouble with extracting the day and month from the meeting title. 
from lines#72-84 you can see an outline of what I was trying to do. i split() the meeting title to get an array of the words in the title, and then check for a month and day in the array. then i create one singular string to use in strptime().
would appreciate any guidance w fixing _parse_start().
everything else works, and i did run isort, black, and flake8.

## Summary

**Issue:** 0051

Replace "ISSUE_NUMBER" with the number of your issue so that GitHub will link this pull request with the issue and make review easier.

## Checklist

All checks are run in [GitHub Actions](https://github.com/features/actions). You'll be able to see the results of the checks at the bottom of the pull request page after it's been opened, and you can click on any of the specific checks listed to see the output of each step and debug failures.

- [ ] Tests are implemented
- [ ] All tests are passing
- [ ] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [ ] Style checks are passing
- [ ] Code comments from template removed

## Questions

Include any questions you have about what you're working on.

### CODE REVIEW

**Comment by jpt-c** [comment]
I'd use a regex to extract date-like strings instead of splitting & searching on your own.

e.g.
test_str =  "Bla bla bla June 4, 2022 etc. "
result = re.findall(r"\w+ \d{1,2}, \d{4}", test_str)
if result:
   return datetime.strptime(result[0], "%B %d, %Y")

& if there isn't a valid date string, you'll need to skip the item

**Comment by haileyhoyat** [comment]
@jpt-c Nice, got it. I appreciate the help, much easier than the way I was doing it. 
This spider is now done.

**Comment by jpt-c** [comment]
great! can you add the test files for this if they exist?

**Comment by haileyhoyat** [comment]
@jpt-c 
yes, sir. test files (test_fresno_housing.py and fresno_housing.html) are tests folder.

**Pull request closed without merging**
