### PR TITLE
test_title() problem as mentioned in Slack

### PR DESCRIPTION
**Pull request by haileyhoyat**
@jpt-c 

spider: fresno_bicycle_pedestrian.py
tests: test_fresno_bicycle_pedestrian.py
webpage: fresno_bicycle_pedestrian.html

note: test_fresno_bicycle_pedestrian.py has all tests commented out for now, going through the tests one by one.

## Summary

**Issue:** #0050

Replace "ISSUE_NUMBER" with the number of your issue so that GitHub will link this pull request with the issue and make review easier.

## Checklist

All checks are run in [GitHub Actions](https://github.com/features/actions). You'll be able to see the results of the checks at the bottom of the pull request page after it's been opened, and you can click on any of the specific checks listed to see the output of each step and debug failures.

- [ ] Tests are implemented
- [ ] All tests are passing
- [ ] Style checks run (see [documentation](https://cityscrapers.org/docs/development/) for more details)
- [ ] Style checks are passing
- [ ] Code comments from template removed

## Questions

Include any questions you have about what you're working on.

### CODE REVIEW

**Comment by jpt-c** [comment]
Somehow your test files both wound up in the wrong folder?  Moving them to where they should be (tests/ and tests/files/) I get the error locally.  The CSS selector `title = item.css("td:nth-child(1) font font::text").get()` does not appear to be correct.

**Comment by haileyhoyat** [comment]
@jpt-c roger that. thanks, working on this now.

**Comment by jpt-c** [comment]
Wanted to check on the status of this one

**Comment by haileyhoyat** [comment]
@jpt-c 

still getting that index error, but i am getting the correct meeting item back in scrapy shell

Screen Shot 2022-08-28 at 11 35 43 AM

Screen Shot 2022-08-28 at 11 35 04 AM

also, i swear i'm constantly running isort/black/flake8 and they always fails CI.

**Comment by haileyhoyat** [comment]
@jpt-c don't do anything, i literally figured it out a minute ago. working on it.

**Pull request closed without merging**
